### ISSUE TITLE
Search function is not working

### ISSUE THREAD

**Issue by alcf-haritha** [argonne-lcf/user-guides#100]
Search seems to be broken. It was working at one point.

**Comment by bethcerny** [comment]
@alcf-haritha please don't forget to assign issues. No one is going to fix unless they know that something is assigned to them. I'll assign this to me.

**Comment by bethcerny** [comment]
This has been fixed. @alcf-haritha 

There is a supplemental javascript file that can’t be crawled that changed at some point. SBX manually moved it over to the Drupal codebase.
 
I’m writing this note to myself for future reference:
/assets/javascripts/workers/search.5bf1dace.min.js
