### ISSUE TITLE
Data Policy page is confusing

### ISSUE THREAD

**Issue by bethcerny** [argonne-lcf/user-guides#105]
Mike contacted me that he was confused by the content on this page:
https://www.alcf.anl.gov/support/user-guides/policies/data-and-software-policies/data-policy/index.html

@alcf-haritha @weallcock I'll take a stab at trying to fix and contact you guys when I get stuck.

**Comment by alcf-haritha** [comment]
Ok

**Comment by alcf-haritha** [comment]
Worked through it on a slack call

**Comment by venkat-1** [comment]
@alcf-haritha @bethcerny  Can this be closed or should this be still open?

**Comment by alcf-haritha** [comment]
I think so, but I'll defer it to @bethcerny since its been so long.

**Comment by bethcerny** [comment]
@alcf-haritha I believe we addressed this a long time ago. I'll close.
