### ISSUE TITLE
Disk Space Quota Management

### ISSUE THREAD

**Issue by bethcerny** [argonne-lcf/user-guides#107]
This content on Disk Space Quota Management doesn't match the title and it's confusing.

Here is the old page in review mode since it is no longer published:
https://www.alcf.anl.gov/node/preview/76c0441c-8f8f-429e-86f6-295d526abcba/full?destination=/admin/content%3Ftitle%3DDisk%2520Space%2520Quota%2520Management%26type%3Duser_guides%26status%3DAll%26langcode%3DAll

**Comment by alcf-haritha** [comment]
What section and page in the current site are you referring to? Also, I can't view the drupal page (even though I am logged in).

**Comment by alcf-haritha** [comment]
@bethcerny What section and page in the current site are you referring to? Also, I can't view the drupal page (even though I am logged in).

**Comment by bethcerny** [comment]
@alcf-haritha you'll have to look at the page in edit mode since it is unpublished. Also, pasting it below. I didn't add it to the GitHub repo because it made no sense. I sent multiple emails to helpdesk@alcfr.anl.gov to get help.

Disk Space Management
For managing disk quotas on Theta and Cooley, please refer to https://www.alcf.anl.gov/support-center/theta/theta-disk-quota for more information. 

For requesting an increase in quota for Director's Discretionary allocations, fill out [this](https://accounts.alcf.anl.gov/allocationRequests) form.

If you need a quota increase for your INCITE/ALCC/ALCC/ESP project directory, please send an email to [support@alcf.anl.gov](mailto:support@alcf.anl.gov) with the machine, project name, new quota amount, and reason for the increase.

For data transfers, please refer to https://www.alcf.anl.gov/support-center/theta/using-globus-theta for Theta and/or https://www.alcf.anl.gov/support-center/cooley/globus-cooley for Cooley

Unix Group Management
As a PI/proxy when you manage your project’s disk space quota, it’s important to remember that users you approve as to be added as project members are also added to the project’s Unix Group.

Unix Group members have the ability to write to the project directory and to access project data. You can manually add or remove Unix Group members at any time by going to https://accounts.alcf.anl.gov/#!/manageUnixGroups

All project members have the ability to run jobs against your allocation and therefore, to potentially impact your project disk space quota. There is no limit to the number of project members you may authorize.

Removing members: When a project member is removed from a project, the Unix group will also be removed. The project member will no longer be able to access project data nor run jobs against your allocation.

**Comment by alcf-haritha** [comment]
Beth, it may be easier to review all the changes in a meeting. Shall I set something up for next week?

**Comment by bethcerny** [comment]
Sure. Next Friday is good.

Alternatively, is there someone on your team who can correct/rewrite it?

Beth

On Oct 23, 2022, at 10:42 PM, alcf-haritha ***@***.***> wrote:

﻿

Beth, it may be easier to review all the changes in a meeting. Shall I set something up for next week?

**Comment by alcf-haritha** [comment]
Friday works for me, I am not sure what changes are needed, so a sit down would benefit me. Lalitha can definitely help out.

**Comment by bethcerny** [comment]
The problem is the text document isn’t about Disk Space Quota Management. It needs a different title or new text.

Beth

On Oct 23, 2022, at 11:08 PM, alcf-haritha ***@***.***> wrote:

﻿

Friday works for me, I am not sure what changes are needed, so a sit down would benefit me. Lalitha can definitely help out.

**Comment by alcf-haritha** [comment]
discussed with Beth on a slack call and I think we are good with what needs to move where. Reassigning to Beth.

**Comment by bethcerny** [comment]
this has been fixed
