### ISSUE TITLE
Accounts Policy page

### ISSUE THREAD

**Issue by bethcerny** [argonne-lcf/user-guides#108]
This page: https://www.alcf.anl.gov/support/user-guides/policies/accounts/accounts-policy/index.html refers to the computing usage policy for ALCF/Argonne National Laboratory. Can this PDF be added?

**Comment by alcf-haritha** [comment]
I will ask the ub3 team for a pdf version of the policies that are displayed as modal popups.

**Comment by alcf-haritha** [comment]
We have the pdfs. Assigning to Jennifer.

**Comment by alcf-haritha** [comment]
merge approved
