### ISSUE TITLE
Header hides beginning of content at anchor link

### ISSUE THREAD

**Issue by zippylab** [argonne-lcf/user-guides#124]
When following a hyperlink to an anchor point, the first part of the content at the anchor point is scrolled up and hidden behind the ALCF header. One simple demonstration is:

1. go to the [Compiling and Linking On Polaris](https://www.alcf.anl.gov/support/user-guides/polaris/compiling-and-linking/compiling-and-linking-overview/index.html) page
2. Click the "Cray Programming Environment" link in the table of contents on the right
3. For me (Chrome Browser on Mac OS), what shows up has both the "Cray Programming Environment" section header and the first line of the paragraph of documentation beginning with "The Cray..." hidden beneath the ALCF header.

**Comment by bethcerny** [comment]
This is being addressed. I hope to have the solution in place before winter break.

**Comment by felker** [comment]
This is fixed, right @zippylab ?

**Comment by zippylab** [comment]
Right, it's fixed
