### ISSUE TITLE
Known Issues?

### ISSUE THREAD

**Issue by bethcerny** [argonne-lcf/user-guides#139]
@cjknight @alcf-haritha Do you know how Polaris "Known Issues" is being kept up-to-date? Is this something that you two are updating regularly?

https://docs.alcf.anl.gov/polaris/known-issues/

**Comment by felker** [comment]
I recently edited it to drop in a known issue--- @zippylab added the C++17 caveat, and @cjknight added the first one. My understanding is that people are ad hoc appending known open bugs, and none have been resolved to date.

**Comment by bethcerny** [comment]
Thanks, @felker. I'll resolve this and ask the UX Committee if someone will take ownership of it.
