### ISSUE TITLE
Broken Polaris link.  Breaks 'make serve'.

### ISSUE THREAD

**Issue by BruceRayWilsonAtANL** [argonne-lcf/user-guides#181]
ERROR    -  Error reading page 'running-jobs/example-job-scripts.md': [Errno 2] No such file or directory:
            '/home/bwilson/DL/github.com/argonne-lcf/user-guides/docs/running-jobs/../../GettingStarted/Examples/Polaris/affinity_gpu/main.cpp'
FileNotFoundError: [Errno 2] No such file or directory: '/home/bwilson/DL/github.com/argonne-lcf/user-guides/docs/running-jobs/../../GettingStarted/Examples/Polaris/affinity_gpu/main.cpp'
make: *** [Makefile:19: serve] Error 1

**Comment by BruceRayWilsonAtANL** [comment]
@felker and @weallcock ^^

**Comment by saforem2** [comment]
@BruceRayWilsonAtANL try

```Shell
python3 -m pip install mkdocs-codeinclude-plugin
git submodule init
git submodule update
```
