### ISSUE TITLE
Add "How to contribute" (and report issues) page

### ISSUE THREAD

**Issue by felker** [argonne-lcf/user-guides#226]
Requested by @alcf-haritha

**Comment by kaushikvelusamy** [comment]
I guess https://github.com/argonne-lcf/user-guides/pull/522 resolved this. 
However, I have asked @bethcerny if it is possible to add a link under the end of "table of contents" in the extras.css style sheet to include "Does this doc need update?" link point to https://docs.alcf.anl.gov/issues/

**Comment by kaushikvelusamy** [comment]
We should also add a guideline preamble on the new issue page to triage and delegate it to the right person faster . Example: https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&projects=&template=documentation.yml

This can be done by following https://docs.github.com/en/enterprise-cloud@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by kaushikvelusamy** [comment]
https://github.com/argonne-lcf/user-guides/pull/572 Addressed it
