### ISSUE TITLE
docs should explain how to setup a local bashrc

### ISSUE THREAD

**Issue by zingale** [argonne-lcf/user-guides#39]
A new account on polaris has no dot files, but often we need to set environment variables for our software builds in a local `.bashrc`.  Looking at `/etc/bash.bashrc`, it seems like the way to do this is to create a `.bash.expert` file where we can place our local variables.  This should be documented somewhere, since I imagine this is a common issue.  Or if there is another preferred file, then that should be explained.

**Comment by felker** [comment]
Is there any problem with simply creating a `~/.bashrc`? I maintain a complete set of `zshrc`, `zshenv`, `bash_login`, `bashrc`, ... in my `$HOME` without any issues. No need to use `.bash.expert`.

**Comment by bethcerny** [comment]
Hi Kyle, Is this resolved or does someone need to do something??

**Comment by felker** [comment]
Closing for now.
