### ISSUE TITLE
Potential discrepancy in DAOS stats

### ISSUE THREAD

**Issue by felker** [argonne-lcf/user-guides#413]
https://github.com/argonne-lcf/user-guides/blob/main/docs/aurora/data-management/daos/aurora-storage-architecture.png
- 220 PB
- 25 TB/s

Compared to some other recent talks like [ATPESC 2023](https://extremecomputingtraining.anl.gov/wp-content/uploads/sites/96/2023/08/ATPESC-2023-Track-1-Talk-3-Servesh-Mulalidharan-Aurora.pdf), which lists:
- 230 PB
- 31 TB/s

The latter figures are more common, I think. What is the right answer?

**Comment by felker** [comment]
@kevin-harms

**Comment by kevin-harms** [comment]
The 220PB number is correct. I can update the ≥ 25TBs to be 31TBs in the image and upload a new version.

**Comment by felker** [comment]
thanks @kevin-harms!

**Comment by felker** [comment]
do you have a new image ready @kevin-harms ?

**Comment by felker** [comment]
I also see from the IAC talk from June 2023 that the DAOS system has 250 PB NVMe at 31 TB/s, but only ~230 PB of usable capacity @ EC16+2
> depends on what users choose for data protection – EC16+2 is erasure code with 16 data chunks and 2 parity chunks (allows surviving 2 failures)

I will just make a new PNG myself, unless you have the PPTX source @kevin-harms
