### ISSUE TITLE
update examples to account for production queue rules

### ISSUE THREAD

**Issue by weallcock** [argonne-lcf/user-guides#47]
Rick submitted ticket RITM0234128  saying he was following the example at https://github.com/argonne-lcf/GettingStarted/blob/master/Examples/Polaris/affinity_gpu/README.md and it didn't work.  The problem is that the example only uses one node, but it doesn't specify -q debug which you have to do now that the production queue rules are in place.  We should scan through / test all the examples and make sure they work with our current production queue scheme.  I assigned Chris because that specific example was his, but everybody will need to check their examples.

**Comment by cjknight** [comment]
@weallcock all examples in README and submit scripts should be fixed now in the GettingStarted repo. Still need to give examples in this repo a quick lookover to see if anything needs updating.
