### ISSUE TITLE
Search function not working in user docs

### ISSUE THREAD

**Issue by jfrancis-anl** [argonne-lcf/user-guides#50]
The search function at the top right corner of help pages doesn't seem to be working. Here's an example of a page where it's not working -- https://www.alcf.anl.gov/support/user-guides/polaris/hardware-overview/machine-overview/index.html

**Comment by bethcerny** [comment]
This has been resolved but I'll wait until it gets pushed to the webserver before I close it.

@jfrancis-anl

**Comment by bethcerny** [comment]
@jfrancis-anl this has been resolved. We're still dealing with a cache purging issue with Varnish but will manually keep an eye out for content to make sure that the search is indexing the new results.
