### ISSUE TITLE
"Running Jobs and Submission Scripts" for Theta page missing

### ISSUE THREAD

**Issue by jfrancis-anl** [argonne-lcf/user-guides#51]
The "Running Jobs and Submission Scripts" for Theta page in Drupal seems to have been lost in the transition of the user help docs. Here's a link to the page in Drupal:

https://www.alcf.anl.gov/support-center/theta/running-jobs-and-submission-scripts

I used to point users to this page a lot whenever they'd have questions about Cobalt and submission scripts. I can't seem to find an equivalent page. Would it be possible to get this moved over?

**Comment by cjknight** [comment]
I believe all of that content should be in this single page now (to help with consistency across resources): https://www.alcf.anl.gov/support/user-guides/theta/queueing-and-running-jobs/job-and-queue-scheduling/index.html .

**Comment by jfrancis-anl** [comment]
That page doesn't have an example Cobalt script though. It covers all of the necessary flags, but having a clear example script for users to learn/play with was helpful. I copied the specific section I would point the users to below. I haven't been able to find another similar example in the documentation.

General information about writing submission scripts:
A very general example submission script is shown below, and specific examples are shown below that. Note that the script must include the aprun command to run the executable on the compute nodes:

#!/bin/bash
#COBALT -t 30 
#COBALT -n 128
#COBALT -q default 
#COBALT --attrs mcdram=cache:numa=quad 
#COBALT -A Catalyst 
echo "Starting Cobalt job script on 128 nodes with 64 ranks on each node" 
echo "with 4 OpenMP threads per rank, for a total of 8192 ranks and 32768 OpenMP threads" 
aprun -n 8192 -N 64 --env OMP_NUM_THREADS=4 -cc depth -d 4 -j 4 myprogram.exe

**Comment by cjknight** [comment]
yeah... creating a Theta example-job-scripts page similar to what we have for Theta would be good:  https://www.alcf.anl.gov/support/user-guides/polaris/queueing-and-running-jobs/example-job-scripts/index.html

**Comment by jfrancis-anl** [comment]
I'm comparing the two pages now, and the "Bundling Multiple Runs into a Script Job" section from the old page might also be a good thing to include.

**Comment by bethcerny** [comment]
Assigning this to Chris. Let me know if you need help.
