### ISSUE TITLE
Left navigation menu hidden by footer when expanded

### ISSUE THREAD

**Issue by atanikan** [argonne-lcf/user-guides#52]
On my browser (Chrome) the left navigation menu when expanded tends to be hidden by the footer making it unreachable. 

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/16871225/186749518-8f0accd8-0bb9-431b-82c0-5291ca591e48.png">

**Comment by bethcerny** [comment]
This is definitely happening in Chrome. I thought the developers fixed, but still needs more work.

**Comment by bethcerny** [comment]
@atanikan I can't recreate this. Can you please tell me which OS and which browser/version that you are using?

**Comment by atanikan** [comment]
Hi Beth, 

Weird now I do see it working fine. Maybe there was a fix that propagated through now? It can be closed
