### ISSUE TITLE
Broken links in the current production repo

### ISSUE THREAD

**Issue by alcf-haritha** [argonne-lcf/user-guides#53]
Add to this list as links are discovered:

- [ ] https://www.alcf.anl.gov/support/user-guides/theta-gpu/getting-started/ : Broken in Software section – “Compiling and Linking on ThetaGPU” pointing to https://argonne-lcf.github.io/docs/theta-gpu/compiling-linking/compiling-and-linking-overview.md
- [ ] Link # 2

**Comment by bethcerny** [comment]
It's probably faster to fix this link than to make an issue. Happy to resolve though.

**Comment by bethcerny** [comment]
this has been resolved
