### ISSUE TITLE
Permission issues on PBS "BigBook"

### ISSUE THREAD

**Issue by bethcerny** [argonne-lcf/user-guides#54]
@weallcock The Box folder that you have the "Big Book" in needs to have permissions changed so that users can view it. Currently returns a prompt Argonne username and password.

Ask @jfrancis-anl for the details. She is the one that discovered it.

**Comment by bethcerny** [comment]
The Box folder still needs the permissions changed so that everyone with a link can read and download.

**Comment by felker** [comment]
Shouldnt be necessary if we merge #68
