### ISSUE TITLE
Top Google result for "alcf polaris user guide" points to old early-access docs repo

### ISSUE THREAD

**Issue by felker** [argonne-lcf/user-guides#66]
Top link is https://www.alcf.anl.gov/support/polaris-userdocs/index.html which seems to point to https://github.com/argonne-lcf/polaris-userdocs. Can the old repo be taken down?

**Comment by cjknight** [comment]
Trying to avoid broken links in search engines. Adding link to current documentation in few places to redirect.

**Comment by felker** [comment]
Apparently fixed with 2022-12-23 change of hosting docs directly out of GitHub, or possibly even earlier.
