### ISSUE TITLE
ALCF User Guides missing favicon

### ISSUE THREAD

**Issue by felker** [argonne-lcf/user-guides#67]
https://www.alcf.anl.gov/support/user-guides/index.html should probably use the same favicon as the main ALCF site: https://alcf.anl.gov/sites/default/files/favicon_1.ico

**Comment by felker** [comment]
The ACDC page also is missing a favicon: https://acdc.alcf.anl.gov/

**Comment by bethcerny** [comment]
Assigning this to me.
