### ISSUE TITLE
Continue to report broken links?

### ISSUE THREAD

**Issue by felker** [argonne-lcf/user-guides#83]
I was searching around for info on Eagle and Grand today and came across several broken links on old non-mkdocs pages, outside the `support/user-guides/` subdomain. In the past I would email media@alcf.anl.gov but was wondering if I should continue to report these, and/or collect them here?

- [ ] https://www.alcf.anl.gov/alcf-community-data-co-op
- [ ] https://www.alcf.anl.gov/support-center/theta-and-thetagpu/eagle-data-sharing

**Comment by bethcerny** [comment]
@felker you should try to fix them. If you can't, assign them to me.

**Comment by felker** [comment]
At some point in the last month, it looks like the https://www.alcf.anl.gov/support-center/theta-and-thetagpu/ might have gotten redirected to the files here. In any case, I didnt note down the pages on which the links were broken, only the broken links, so I have no way of knowing where they are right now. 

Except some old facility updates, which I am not sure if they are worth fixing since there are so many:
https://alcf.anl.gov/support-center/facility-updates/community-data-sharing-services-eagle-0
